import { jsPDF } from 'jspdf'
import type { Army } from '../types/army'
import { getFactionDisplayName, getFactionColor } from '../utils/factions'
import { getRoleLabel } from '../data/battlefieldRoles'

function getTotalPoints(army: Army): number {
  return army.units.reduce((sum, u) => sum + u.count * u.pointsPerModel, 0)
}

function groupByRole(army: Army) {
  const groups = new Map<string, typeof army.units>()
  for (const unit of army.units) {
    const list = groups.get(unit.role) || []
    list.push(unit)
    groups.set(unit.role, list)
  }
  return groups
}

export function exportAsText(army: Army): string {
  const total = getTotalPoints(army)
  const lines: string[] = [
    `=== ${army.name} ===`,
    `Points: ${total} / ${army.pointsLimit}`,
    '',
  ]

  const groups = groupByRole(army)
  for (const [role, units] of groups) {
    lines.push(`── ${getRoleLabel(role)} ──`)
    for (const u of units) {
      const pts = u.count * u.pointsPerModel
      const faction = getFactionDisplayName(u.faction)
      lines.push(`  ${u.unitName} x${u.count} — ${pts} pts [${faction}]`)
    }
    lines.push('')
  }

  lines.push(`Total: ${total} pts`)
  lines.push(`Generated by Battle Scanner`)
  return lines.join('\n')
}

export function exportAsPdf(army: Army): void {
  const doc = new jsPDF()
  const total = getTotalPoints(army)

  // Title
  doc.setFontSize(20)
  doc.text(army.name, 20, 25)

  // Points
  doc.setFontSize(12)
  doc.setTextColor(100)
  doc.text(`${total} / ${army.pointsLimit} points`, 20, 35)

  let y = 50
  const groups = groupByRole(army)

  for (const [role, units] of groups) {
    if (y > 260) {
      doc.addPage()
      y = 20
    }

    // Role header
    doc.setFontSize(14)
    doc.setTextColor(0)
    doc.text(getRoleLabel(role), 20, y)
    y += 8

    doc.setFontSize(10)
    doc.setTextColor(60)

    for (const u of units) {
      if (y > 270) {
        doc.addPage()
        y = 20
      }
      const pts = u.count * u.pointsPerModel
      const faction = getFactionDisplayName(u.faction)
      doc.text(`${u.unitName} x${u.count} — ${pts} pts [${faction}]`, 25, y)
      y += 6
    }

    y += 4
  }

  // Footer
  if (y > 270) {
    doc.addPage()
    y = 20
  }
  doc.setFontSize(8)
  doc.setTextColor(150)
  doc.text('Generated by Battle Scanner', 20, y + 10)

  doc.save(`${army.name.replace(/[^a-zA-Z0-9]/g, '_')}.pdf`)
}

export function copyToClipboard(text: string): Promise<void> {
  return navigator.clipboard.writeText(text)
}
